import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from './components/Header'
import Hero from './components/Hero'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-max w-screen snap-y snap-mandatory overflow-scroll z-0'>
      <Head>
        <title>Rwitesh Bera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* Head
      er  */}
      <Header />

      {/* Hero  */}
      <section className='snap-center'>
      <Hero />
      </section>

      {/* About  */}

      {/* Volunteering Experience  */}

      {/* Projects  */}

      {/* Contact Me  */}
    </div>
  )
}
